# version: '3.8'

# services:
#   backend:
#     build: ./app/backend
#     ports:
#       - "8000:8000"
#     environment:
#       - DB_HOST=postgres
#     depends_on:
#       - postgres
#       - neo4j

#   postgres:
#     image: postgres:15
#     ports:
#       - "5432:5432"

#   neo4j:
#     image: neo4j:5.12
#     ports:
#       - "7474:7474"
#       - "7687:7687"