CREATE TABLE IF NOT EXISTS mcp_mutations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    action VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'in_progress',
    result_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_mcp_mutations_user_action_key UNIQUE (user_id, action, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_mcp_mutations_user_id ON mcp_mutations(user_id);
CREATE INDEX IF NOT EXISTS idx_mcp_mutations_status ON mcp_mutations(status);
