# FROM python:3.11-slim

# WORKDIR /app

# # 백엔드 전용 requirements만 복사해서 설치
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# # 백엔드 코드 전체 복사
# COPY . .

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
