-- Bobbeori MVP PostgreSQL schema
-- 밥벌이 MVP PostgreSQL 스키마

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(100) NOT NULL,
    auth_provider VARCHAR(50),
    provider_user_id VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE users IS '사용자';
COMMENT ON COLUMN users.id IS '사용자ID';
COMMENT ON COLUMN users.email IS '이메일';
COMMENT ON COLUMN users.nickname IS '닉네임';
COMMENT ON COLUMN users.auth_provider IS '가입채널';
COMMENT ON COLUMN users.provider_user_id IS '소셜고유ID';
COMMENT ON COLUMN users.created_at IS '생성일시';

CREATE TABLE user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    allergies TEXT,
    disliked_ingredients TEXT,
    preferred_ingredients TEXT,
    allow_expiry_alert BOOLEAN NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE user_preferences IS '사용자설정';
COMMENT ON COLUMN user_preferences.id IS '사용자설정ID';
COMMENT ON COLUMN user_preferences.user_id IS '사용자ID';
COMMENT ON COLUMN user_preferences.allergies IS '알레르기정보';
COMMENT ON COLUMN user_preferences.disliked_ingredients IS '비선호식재료';
COMMENT ON COLUMN user_preferences.preferred_ingredients IS '선호식재료';
COMMENT ON COLUMN user_preferences.allow_expiry_alert IS '소비기한알림허용여부';

CREATE TABLE calendar_integrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(50) NOT NULL DEFAULT 'google',
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    expires_at TIMESTAMPTZ,
    calendar_id VARCHAR(255) NOT NULL DEFAULT 'primary',
    connected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_calendar_integrations_user_provider UNIQUE (user_id, provider)
);

CREATE INDEX idx_calendar_integrations_user_id ON calendar_integrations(user_id);

COMMENT ON TABLE calendar_integrations IS '캘린더연동';
COMMENT ON COLUMN calendar_integrations.id IS '캘린더연동ID';
COMMENT ON COLUMN calendar_integrations.user_id IS '사용자ID';
COMMENT ON COLUMN calendar_integrations.provider IS '캘린더제공자';
COMMENT ON COLUMN calendar_integrations.access_token IS '암호화AccessToken';
COMMENT ON COLUMN calendar_integrations.refresh_token IS '암호화RefreshToken';
COMMENT ON COLUMN calendar_integrations.expires_at IS 'AccessToken만료일시';
COMMENT ON COLUMN calendar_integrations.calendar_id IS '캘린더ID';
COMMENT ON COLUMN calendar_integrations.connected_at IS '연결일시';
COMMENT ON COLUMN calendar_integrations.updated_at IS '수정일시';

CREATE TABLE calendar_event_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_key VARCHAR(255) NOT NULL,
    event_type VARCHAR(50),
    summary VARCHAR(255),
    target_date DATE,
    google_event_id VARCHAR(255),
    html_link VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    source VARCHAR(30) NOT NULL DEFAULT 'manual',
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_calendar_event_logs_user_id ON calendar_event_logs(user_id);
CREATE INDEX idx_calendar_event_logs_created_at ON calendar_event_logs(created_at);
CREATE INDEX idx_calendar_event_logs_event_key ON calendar_event_logs(event_key);

CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(100),
    default_unit VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE ingredients IS '식재료';
COMMENT ON COLUMN ingredients.id IS '식재료ID';
COMMENT ON COLUMN ingredients.name IS '식재료명';
COMMENT ON COLUMN ingredients.normalized_name IS '정규화명';
COMMENT ON COLUMN ingredients.category IS '분류';
COMMENT ON COLUMN ingredients.default_unit IS '기본단위';
COMMENT ON COLUMN ingredients.created_at IS '생성일시';

CREATE TABLE ingredient_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    alias_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ingredient_aliases_ingredient_alias UNIQUE (ingredient_id, alias_name)
);

COMMENT ON TABLE ingredient_aliases IS '식재료별칭';
COMMENT ON COLUMN ingredient_aliases.id IS '별칭ID';
COMMENT ON COLUMN ingredient_aliases.ingredient_id IS '식재료ID';
COMMENT ON COLUMN ingredient_aliases.alias_name IS '별칭명';
COMMENT ON COLUMN ingredient_aliases.created_at IS '생성일시';

CREATE TABLE ingredient_storage_standards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    storage_location VARCHAR(50) NOT NULL,
    lifespan_days INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ingredient_storage_standards UNIQUE (ingredient_id, storage_location)
);

COMMENT ON TABLE ingredient_storage_standards IS '식재료 보관 기준 (수명 캐시)';
COMMENT ON COLUMN ingredient_storage_standards.id IS '기준ID';
COMMENT ON COLUMN ingredient_storage_standards.ingredient_id IS '식재료ID';
COMMENT ON COLUMN ingredient_storage_standards.storage_location IS '보관위치';
COMMENT ON COLUMN ingredient_storage_standards.lifespan_days IS '보관가능일수';
COMMENT ON COLUMN ingredient_storage_standards.created_at IS '생성일시';

CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    original_file_name VARCHAR(255),
    store_name TEXT,
    purchased_at TIMESTAMPTZ,
    total_price INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE receipts IS '영수증';
COMMENT ON COLUMN receipts.id IS '영수증ID';
COMMENT ON COLUMN receipts.user_id IS '사용자ID';
COMMENT ON COLUMN receipts.original_file_name IS '원본파일명';
COMMENT ON COLUMN receipts.store_name IS '구매장소';
COMMENT ON COLUMN receipts.purchased_at IS '구매일시';
COMMENT ON COLUMN receipts.total_price IS '총가격';
COMMENT ON COLUMN receipts.created_at IS '생성일시';

CREATE TABLE receipt_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
    ingredient_id BIGINT REFERENCES ingredients(id) ON DELETE SET NULL,
    raw_item_name VARCHAR(255) NOT NULL,
    normalized_item_name VARCHAR(255),
    quantity NUMERIC(10, 2),
    unit VARCHAR(30),
    price INTEGER,
    is_food BOOLEAN,
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE receipt_items IS '영수증품목';
COMMENT ON COLUMN receipt_items.id IS '영수증품목ID';
COMMENT ON COLUMN receipt_items.receipt_id IS '영수증ID';
COMMENT ON COLUMN receipt_items.ingredient_id IS '식재료ID';
COMMENT ON COLUMN receipt_items.raw_item_name IS '원본품목명';
COMMENT ON COLUMN receipt_items.normalized_item_name IS '정규화품목명';
COMMENT ON COLUMN receipt_items.quantity IS '수량';
COMMENT ON COLUMN receipt_items.unit IS '단위';
COMMENT ON COLUMN receipt_items.price IS '가격';
COMMENT ON COLUMN receipt_items.is_food IS '식품여부';
COMMENT ON COLUMN receipt_items.memo IS '메모';
COMMENT ON COLUMN receipt_items.created_at IS '생성일시';

CREATE TABLE fridge_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE RESTRICT,
    receipt_item_id BIGINT REFERENCES receipt_items(id) ON DELETE SET NULL,
    display_name VARCHAR(255),
    quantity NUMERIC(10, 2),
    unit VARCHAR(30),
    storage_location VARCHAR(50),
    purchased_date DATE,
    expiry_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'normal',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_fridge_items_status
        CHECK (status IN ('normal', 'expiring', 'expired', 'used'))
);

COMMENT ON TABLE fridge_items IS '보유재료';
COMMENT ON COLUMN fridge_items.id IS '보유재료ID';
COMMENT ON COLUMN fridge_items.user_id IS '사용자ID';
COMMENT ON COLUMN fridge_items.ingredient_id IS '식재료ID';
COMMENT ON COLUMN fridge_items.receipt_item_id IS '영수증품목ID';
COMMENT ON COLUMN fridge_items.display_name IS '표시재료명';
COMMENT ON COLUMN fridge_items.quantity IS '수량';
COMMENT ON COLUMN fridge_items.unit IS '단위';
COMMENT ON COLUMN fridge_items.storage_location IS '보관위치';
COMMENT ON COLUMN fridge_items.purchased_date IS '구매일';
COMMENT ON COLUMN fridge_items.expiry_date IS '소비기한';
COMMENT ON COLUMN fridge_items.status IS '상태';
COMMENT ON COLUMN fridge_items.created_at IS '생성일시';

CREATE TABLE ingredient_guides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL UNIQUE REFERENCES ingredients(id) ON DELETE CASCADE,
    storage_location VARCHAR(50),
    storage_method TEXT,
    prep_method TEXT,
    wash_method TEXT,
    freshness_check TEXT,
    caution TEXT,
    source_url VARCHAR(500),
    validation_status VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE ingredient_guides IS '식재료가이드';
COMMENT ON COLUMN ingredient_guides.id IS '가이드ID';
COMMENT ON COLUMN ingredient_guides.ingredient_id IS '식재료ID';
COMMENT ON COLUMN ingredient_guides.storage_location IS '보관위치';
COMMENT ON COLUMN ingredient_guides.storage_method IS '보관방법';
COMMENT ON COLUMN ingredient_guides.prep_method IS '손질방법';
COMMENT ON COLUMN ingredient_guides.wash_method IS '세척방법';
COMMENT ON COLUMN ingredient_guides.freshness_check IS '신선도체크방법';
COMMENT ON COLUMN ingredient_guides.caution IS '주의문구';
COMMENT ON COLUMN ingredient_guides.source_url IS '출처URL';
COMMENT ON COLUMN ingredient_guides.validation_status IS '검수상태';
COMMENT ON COLUMN ingredient_guides.created_at IS '생성일시';

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100),
    serving_size INTEGER,
    cooking_time INTEGER,
    difficulty VARCHAR(50),
    image_url VARCHAR(500),
    source_url VARCHAR(500),
    recipe_steps JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE recipes IS '레시피';
COMMENT ON COLUMN recipes.id IS '레시피ID';
COMMENT ON COLUMN recipes.title IS '레시피명';
COMMENT ON COLUMN recipes.description IS '설명';
COMMENT ON COLUMN recipes.category IS '카테고리';
COMMENT ON COLUMN recipes.serving_size IS '기준인분';
COMMENT ON COLUMN recipes.cooking_time IS '조리시간';
COMMENT ON COLUMN recipes.difficulty IS '난이도';
COMMENT ON COLUMN recipes.image_url IS '이미지URL';
COMMENT ON COLUMN recipes.source_url IS '출처URL';
COMMENT ON COLUMN recipes.recipe_steps IS '조리단계 JSON 배열';
COMMENT ON COLUMN recipes.created_at IS '생성일시';

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE RESTRICT,
    raw_ingredient_name VARCHAR(255),
    required_quantity NUMERIC(10, 2),
    unit VARCHAR(30),
    is_main_ingredient BOOLEAN NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE recipe_ingredients IS '레시피재료';
COMMENT ON COLUMN recipe_ingredients.id IS '레시피재료ID';
COMMENT ON COLUMN recipe_ingredients.recipe_id IS '레시피ID';
COMMENT ON COLUMN recipe_ingredients.ingredient_id IS '식재료ID';
COMMENT ON COLUMN recipe_ingredients.raw_ingredient_name IS '원본재료명';
COMMENT ON COLUMN recipe_ingredients.required_quantity IS '필요수량';
COMMENT ON COLUMN recipe_ingredients.unit IS '단위';
COMMENT ON COLUMN recipe_ingredients.is_main_ingredient IS '주재료여부';

CREATE TABLE recommendation_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    recommendation_type VARCHAR(50),
    match_score NUMERIC(5, 2),
    owned_ingredient_count INTEGER,
    missing_ingredient_count INTEGER,
    missing_ingredients TEXT,
    rank_no INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE recommendation_results IS '추천결과';
COMMENT ON COLUMN recommendation_results.id IS '추천결과ID';
COMMENT ON COLUMN recommendation_results.user_id IS '사용자ID';
COMMENT ON COLUMN recommendation_results.recipe_id IS '레시피ID';
COMMENT ON COLUMN recommendation_results.recommendation_type IS '추천유형';
COMMENT ON COLUMN recommendation_results.match_score IS '매칭점수';
COMMENT ON COLUMN recommendation_results.owned_ingredient_count IS '보유재료수';
COMMENT ON COLUMN recommendation_results.missing_ingredient_count IS '부족재료수';
COMMENT ON COLUMN recommendation_results.missing_ingredients IS '부족재료목록';
COMMENT ON COLUMN recommendation_results.rank_no IS '추천순위';
COMMENT ON COLUMN recommendation_results.created_at IS '생성일시';

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fridge_item_id BIGINT NOT NULL REFERENCES fridge_items(id) ON DELETE CASCADE,
    notification_type VARCHAR(50) NOT NULL,
    target_date DATE,
    message TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ,
    CONSTRAINT ck_notifications_type
        CHECK (notification_type IN ('expiring_soon', 'expired')),
    CONSTRAINT ck_notifications_status
        CHECK (status IN ('pending', 'sent', 'read', 'failed'))
);

COMMENT ON TABLE notifications IS '알림';
COMMENT ON COLUMN notifications.id IS '알림ID';
COMMENT ON COLUMN notifications.user_id IS '사용자ID';
COMMENT ON COLUMN notifications.fridge_item_id IS '보유재료ID';
COMMENT ON COLUMN notifications.notification_type IS '알림유형';
COMMENT ON COLUMN notifications.target_date IS '대상일자';
COMMENT ON COLUMN notifications.message IS '메시지';
COMMENT ON COLUMN notifications.status IS '상태';
COMMENT ON COLUMN notifications.created_at IS '생성일시';
COMMENT ON COLUMN notifications.sent_at IS '발송일시';

CREATE INDEX idx_user_preferences_user_id ON user_preferences(user_id);
CREATE INDEX idx_ingredient_aliases_alias_name ON ingredient_aliases(alias_name);
CREATE INDEX idx_fridge_items_user_id ON fridge_items(user_id);
CREATE INDEX idx_fridge_items_ingredient_id ON fridge_items(ingredient_id);
CREATE INDEX idx_fridge_items_receipt_item_id ON fridge_items(receipt_item_id);
CREATE INDEX idx_fridge_items_expiry_date ON fridge_items(expiry_date);
CREATE INDEX idx_receipts_user_id ON receipts(user_id);
CREATE INDEX idx_receipt_items_receipt_id ON receipt_items(receipt_id);
CREATE INDEX idx_receipt_items_ingredient_id ON receipt_items(ingredient_id);
CREATE INDEX idx_recipe_ingredients_recipe_id ON recipe_ingredients(recipe_id);
CREATE INDEX idx_recipe_ingredients_ingredient_id ON recipe_ingredients(ingredient_id);
CREATE INDEX idx_recommendation_results_user_id ON recommendation_results(user_id);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_fridge_item_id ON notifications(fridge_item_id);
CREATE INDEX idx_notifications_status ON notifications(status);
